### ISSUE TITLE
Switch to using an API upload token?

### ISSUE THREAD

**Issue by ncoghlan** [joerick/cibuildwheel-autopypi-example#6]
Now that PyPI supports using API upload tokens for deployments, it would be nice to use that in this example.

Travis cover using an API token with their native deployment tooling here: https://docs.travis-ci.com/user/deployment/pypi/

The main API token docs are here: https://pypi.org/help/#apitoken

The minimalist update to the current example would be to:

1. Change the example username to `__token__`
2. Note that `TWINE_PASSWORD` needs to be set to the API token, rather than the user password

**Comment by joerick** [comment]
Hi @ncoghlan ! Thanks for the note! We've been tracking this over in https://github.com/joerick/cibuildwheel/issues/154, too. I've been holding off on recommending this quite yet because I think the feature is still in beta, in case something changes. Is that still the case, or is this very likely to be stable from now on?

**Comment by ncoghlan** [comment]
My understanding is that the beta testing is going well, so incompatible changes are unlikely, but tagging @brainwane to ask if there is an ETA for the "beta" qualifier being dropped.

**Comment by brainwane** [comment]
Good question! https://github.com/pypa/warehouse/issues/5661#issuecomment-515802931 is where I've been tracking what we need in order for the API token feature to emerge from beta. Right now there's a hard-to-understand error on the command line when users have a particular kind of credential problem pypa/warehouse#6232 , and I believe announcing the feature without fixing that would lead to a bunch of support requests and similar headaches. I've asked Warehouse developers to expedite fixing it so we can come out of beta.

**Comment by joerick** [comment]
Thanks @brainwane ! Looks like things are moving, I'll keep an eye on those threads

**Comment by joerick** [comment]
Done! Thank you both!

**Comment by ncoghlan** [comment]
Thank *you* for cibuildwheel!

**Comment by brainwane** [comment]
@joerick and @ncoghlan thanks for causing me to take a fresh look and re-nudge the beta features!
